// import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My first App with Nextjs 13',
  description: 'Generated by create next app',
}
import Navigations from "@/components/Navigations"
//import Link from "next/link"

const links = [{
  label: 'Home',
  route: '/'
},{
  label: 'AboutPage',
  route: '/about'
}
]

export default function RootLayout({ children }) {
  return (
    <html>
      <head>
        <title>My first App with Nextjs 13</title>
        <link rel='stylesheet' href='https://bootswatch.com/5/flatly/bootstrap.min.css' />
      </head>
      <body >
        <header>
          <Navigations />
        </header>
        <div className="container p-4">
          {children}
        </div>
      </body>
    </html>
  )
}
